Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/09/2023
Var
contador : inteiro


Inicio
// REPETICAO WHILE
contador <- 1
enquanto (contador <= 10) faca
 escreval("Esta é uma mensagem repetida", contador," vezes")
 contador <- contador + 1
fimEnquanto



Fimalgoritmo