Algoritmo "correção 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/09/2023
Var
numero, resultado : inteiro

Inicio
escreva("digite um número para visualizar seu antecessor")
leia(numero)

escreva ("o antecessor do numero é: ",numero - 1)

Fimalgoritmo