Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/09/2023
Var
quantidade, valor, código inteiro

Inicio
escreval("digite código de produto")
leia("codigo")
escreval("quantidade de produtos")
leia("quantidade")
escreval("valor dos produtos")
leia("valor")
escreval("")
escreval("")


Fimalgoritmo