Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/09/2023
Var
brancos, nulos , válidos : inteiro


Inicio
escreval("votos brancos")
leia(brancos)
escreval("votos nulos")
leia(nulos)
escreval("votos válidos")
leia(válidos)

 escreva("o resultado é de ",
fimFuncao
 
escreval(soma())


Fimalgoritmo