Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/09/2023
Var
numero : inteiro


Inicio
Defina número[10];
Defina Total;

número = [1,5,6,0,4,8,3,1,8,7];

Enquanto(i=1, i<=10, i++){
Total = Total + número[i];
}

Escreva Total;

Fimalgoritmo





